#!/bin/bash -e

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2021-2022, Marcin Ślusarz <marcin.slusarz@gmail.com>

set -o pipefail

filter=
filteropt=
treeopts=
cutopts=
OPTIND=1

incolumns=euid_name,pid,ppid,%cpu,vm_rss_KiB,tty_id,state,start_time,cpu_time,processor,command
outcolumns=euid_name,pid,ppid,%cpu,vm_rss_KiB,vm_rss_KiB_sum,tty_id,state,start_time,cpu_time,processor,command

while getopts "f:LsS" opt; do
    case "$opt" in
    f)  filter=--filter
        filteropt="$OPTARG"
        ;;
    L)  treeopts=-L
        outcolumns=level,$outcolumns
        ;;
    s)  cutopts=-s
        ;;
    S)  cutopts=-S
        ;;
    esac
done

shift $((OPTIND-1))

csv-ps -c $incolumns "$@" | \
	csv-tree --key pid --parent ppid --indent command --sum vm_rss_KiB,vm_rss_KiB_sum $treeopts $filter "$filteropt" | \
	csv-cut -c $outcolumns $cutopts
