#!/bin/bash -e

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2021, Marcin Ślusarz <marcin.slusarz@gmail.com>

set -o pipefail

show=
indentcol=name
OPTIND=1

while getopts "fsS" opt; do
    case "$opt" in
    f)  indentcol=full_path
        ;;
    s)  show=-s
        ;;
    S)  show=-S
        ;;
    esac
done

shift $((OPTIND-1))

csv-ls -a -c full_path,parent,name,size -R "$@" | \
	csv-grep -v -c name -x -F . -c name -x -F .. | \
	csv-tree --key full_path --parent parent --indent $indentcol --sum size | \
	csv-cut -c size,$indentcol $show
