#!/bin/bash -e

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2021-2022, Marcin Ślusarz <marcin.slusarz@gmail.com>

set -o pipefail

filter=
filteropt=
level=
treeopts=
cutopts=
OPTIND=1

while getopts "f:LsS" opt; do
    case "$opt" in
    f)  filter=--filter
        filteropt="$OPTARG"
        ;;
    L)  treeopts=-L
        level=level,
        ;;
    s)  cutopts=-s
        ;;
    S)  cutopts=-S
        ;;
    esac
done

columns=euid_name,pid,ppid,%cpu,vm_rss_KiB,tty_id,state,start_time,cpu_time,processor,command

shift $((OPTIND-1))

csv-ps -c $columns "$@" | \
	csv-tree --key pid --parent ppid --indent command --sum vm_rss_KiB $treeopts $filter "$filteropt" | \
	csv-cut -c $level$columns $cutopts
