name: Coverage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: update package lists
      run: sudo apt update
    - name: install dependencies
      run: sudo apt install build-essential cmake pkg-config flex bison libsqlite3-dev libprocps-dev libncursesw5-dev libmnl-dev tmux gnuplot
    - name: create build directory
      run: mkdir build
    - name: configure
      run: cd build && cmake .. -DCMAKE_INSTALL_PREFIX=/tmp/csv-nix-tools-bin -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=ON
    - name: build
      run: cd build && make
    - name: install
      run: cd build && make install
    - name: test
      run: cd build && ctest --output-on-failure --timeout 60
    - name: upload coverage results
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
