name: Coverity

on:
  schedule:
    - cron:  '17 18 * * 5' # fridays 18:17

env:
  COVNAME: mslusarz/csv-nix-tools

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: current time
        run: date

      - name: checkout
        uses: actions/checkout@v2

      - name: update package lists
        run: sudo apt update

      - name: install dependencies
        run: sudo apt install build-essential cmake pkg-config flex bison libsqlite3-dev libprocps-dev libncursesw5-dev libmnl-dev curl

      - name: download Coverity
        run: |
          curl -o cov-analysis-linux64.tar.gz https://scan.coverity.com/download/cxx/linux64 --form project=$COVNAME --form token=$TOKEN
          mkdir cov-analysis-linux64
          tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}

      - name: configure
        run: cmake -B build . -DCMAKE_BUILD_TYPE=Debug

      - name: Coverity build
        run: |
          export PATH=`pwd`/cov-analysis-linux64/bin:$PATH
          cd build
          cov-build --dir cov-int make

      - name: submit results
        run: |
          cd build
          tar czvf cnt.tgz cov-int
          curl \
            --form project=$COVNAME \
            --form token=$TOKEN \
            --form email=$EMAIL \
            --form file=@cnt.tgz \
            --form version="`git describe --tags --always`" \
            --form description="`git log -1 --oneline HEAD`" \
            https://scan.coverity.com/builds?project=$COVNAME
        env:
          EMAIL: ${{ secrets.COVERITY_SCAN_NOTIFICATION_EMAIL }}
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
